=== Tiagomf29/microservices-trein/ms-sale/src/main/resources/Customer-information.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mssale.com" xmlns:tns="http://mssale.com" elementFormDefault="qualified">

	<xs:element name="GetSalesDetailByIdRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="GetSalesDetailByIdResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SalesDetail" type="tns:SalesDetail"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<!--  -->
	
	<xs:element name="GetAllSalesRequest">
		<xs:complexType>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="GetAllSalesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SalesDetail" type="tns:SalesDetail" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!--  -->	
	
	<xs:element name="InsertSalesRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dataHora" type="xs:dateTime"/>
				<xs:element name="productId" type="xs:integer"/>
				<xs:element name="personId" type="xs:integer"/>
				<xs:element name="quantity" type="xs:integer"/>			
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
	<xs:element name="InsertSalesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="defaultMessage"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
		<!--  -->	
	
	<xs:element name="UpdateSalesRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SalesDetail" type="tns:SalesDetail"/>		
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
	<xs:element name="UpdateSalesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="defaultMessage"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!--  -->
	
	<xs:element name="DeleteSalesDetailByIdRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:integer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="DeleteSalesDetailByIdResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="defaultMessage"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	
	<!--  -->	
	
	<xs:complexType name="SalesDetail">
		<xs:sequence>
			<xs:element name="id" type="xs:integer"/>
			<xs:element name="dataHora" type="xs:dateTime"/>
			<xs:element name="productId" type="xs:integer"/>
			<xs:element name="productName" type="xs:string"/>
			<xs:element name="personId" type="xs:integer"/>
			<xs:element name="personName" type="xs:string"/>
			<xs:element name="quantity" type="xs:integer"/>			
		</xs:sequence>
	</xs:complexType>	

</xs:schema>

=== Tiagomf29/microservices-trein/ms-sale/files-xml/Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<GetSalesDetailByIdResponse xmlns="http://mssale.com"
						   xsi:schemaLocation="http://mssale.com Customer-information.xsd"
					       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<SalesDetail>
		<id>123</id>
		<dataHora>2021-04-29T00:00:00</dataHora>
		<productId>1</productId>
		<productName>Bola</productName>
		<personId>1</personId>
		<personName>Tiago</personName>
		<quantity>10</quantity>
	</SalesDetail>
</GetSalesDetailByIdResponse>
